### PR TITLE
Improvement of the Czech translation

### PR DESCRIPTION
**Pull request by ikanakova**

### CODE REVIEW

**Comment by arnowelzel** [comment]
Thanks for the update. However any translation needs to updated at Crowdin: https://crowdin.com/project/periodical - otherwise it will be overwritten with a translation update. If you can not do this on your own, please let me know, then I will use your PR to transfer the changes manually.

**Comment by ikanakova** [comment]
Sorry, I'll translate in Crowdin.

**Comment by ikanakova** [comment]
Would it be possible to make me a proofreader at Crowdin?

**Comment by ikanakova** [comment]
Or please approve my suggested string changes in Crowdin.

**Comment by igefa-awelzel** [comment]
I made you a proofreader for Czech in Crowdin - thanks for your support!

**Comment by arnowelzel** [comment]
I made you a proofreader for Czech in Crowdin - thanks for your support!

**Pull request closed without merging**
